### ISSUE TITLE
Syntax error on a multi-row template

### ISSUE THREAD

**Issue by dustin** [haskellari/postgresql-simple#106]
I've got this error on what seems to be a pretty simple query.

```
FormatError {fmtMessage = "syntax error in multi-row template",
             fmtQuery = "update metablob set meta = null, backedup = true where media_id = ?",
             fmtParams = []}
```

It's unclear to me the syntax error is.  This is a chunk of code I've been migrating from SQLite and I'd expect this to work without issue.

**Comment by dustin** [comment]
OK, well, the query's right there.  Having read the source code, I see where the bug is.  This is just a duplicate of #58

**Comment by phadej** [comment]
By reproducer I meant how the library was used, in particular Haskell code. (I had to guess you used `executeMany` where you probably wanted something else).

Closing as confirmed to be a duplicate.
