### ISSUE TITLE
Negative dates and timestamps are not parsed

### ISSUE THREAD

**Issue by pbrinkmeier** [haskellari/postgresql-simple#126]
I was wondering how `postgresql-simple` treats the February 29th, 1 BC. This is a valid date in Postgres, since it considers 1 BC a leap year according to how the proleptic Gregorian calendar was practiced historically (no year zero):

```
ghci> conn <- connectPostgreSQL "..."
ghci> xs :: [Only String] <- query_ conn "select date 'February 29, 1 BC' :: text"
ghci> xs
[Only {fromOnly = "0001-02-29 BC"}]
```

(I am using a Postgres 14 Docker image without further configuration.)

However, `postgresql-simple` fails to convert this into a `Day`:

```
ghci> xs :: [Only Day] <- query_ conn "select date 'February 29, 1 BC'"
*** Exception: ConversionFailed {errSQLType = "date", errSQLTableOid = Nothing, errSQLField = "date", errHaskellType = "Day", errMessage = "Failed reading: invalid date"}
```

This fails because the [`day` parser](https://hackage.haskell.org/package/postgresql-simple-0.7.0.0/docs/src/Database.PostgreSQL.Simple.Time.Internal.Parser.html#day) ignores the `BC` suffix and calls `fromGregorianValid 1 2 29`, which fails because 1 isn't a leap year.

Since `postgresql-simple` doesn't handle the `BC` suffix , it can't decode negative dates at all:

```
ghci> xs :: [Only Day] <- query_ conn "select date 'January 1, 1 BC'"
*** Exception: ConversionFailed {errSQLType = "date", errSQLTableOid = Nothing, errSQLField = "date", errHaskellType = "Day", errMessage = "endOfInput"}
```

 I was wondering whether you would accept either

* a PR that improves error messages and comments around this issue
* or a PR that adds the BC case to the parser.

In the second case, one would have to figure out how to represent February 29, 1 BC, as it doesn't exist in the astronomical calendar used by `Day` (and therefore `UTCTime`).

**Comment by phadej** [comment]
Isn''t "February 29 1BC" what `Day` represents as `0000-02-29' (and 2 BC, is year -0001 etc)?

```haskell
*Data.Time.Calendar> fromGregorianValid 0 2 29
Just 0000-02-29
*Data.Time.Calendar> fromGregorianValid (-1) 2 28
Just -0001-02-28
```

Can postgres be configured to output ISO dates:

An expanded year representation [±YYYYY] must have an agreed-upon number of extra year digits beyond the four-digit minimum, and it must be prefixed with a + or − sign[21] instead of the more common AD/BC (or CE/BCE) notation; by convention 1 BC is labelled +0000, 2 BC is labeled −0001, and so on.

https://en.wikipedia.org/wiki/ISO_8601#Years

**Comment by pbrinkmeier** [comment]
> Isn''t "February 29 1BC" what Day represents as `0000-02-29' (and 2 BC, is year -0001 etc)?

That's right, but it would still warrant a comment imo. Something like "`Show Day` displays negative days offset by one from the way Postgres does".

> Can postgres be configured to output ISO dates:

I haven't researched it yet but it should be possible. Postgres actually [treats 1 BC as zero for storage](https://www.postgresql.org/docs/current/datetime-input-rules.html) though, so it might just be behind some flag. In any case, this should be documented somewhere.

**Comment by phadej** [comment]
My (old) postgresql server is buggy:

```
phadej=# select to_date('-0000-10-10', 'YYYY-MM-DD');
    to_date    
---------------
 0001-10-10 BC
(1 row)

phadej=# select to_date('-0001-10-10', 'YYYY-MM-DD');
    to_date    
---------------
 0001-10-10 BC
(1 row)
```

and `to_char` doesn't have a format option to output negative years.

I'm very surprised about this behavior. I guess we are out of luck, and better to change parsers to also look for `BC`/`AD` suffixes.

**Comment by pbrinkmeier** [comment]
```
select to_date('-0000-10-10', 'YYYY-MM-DD');
```

Oh no. That's kinda amazing.

I don't think Postgres ever outputs `AD`, but I can check it out in the next days and prepare a PR if you like.

**Comment by pbrinkmeier** [comment]
The [`EncodeDateTime`](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/datetime.c#l4214) function in Postgres is responsible for turning `struct pg_tm` (derived from `Timestamp`/`TimestampTz`) into a textual representation.

It seems to me that `struct pg_tm` actually uses an astromical calendar as well, since they subtract one from the year before negating it where it's output, e.g. [here](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/datetime.c#l4248):

```
str = pg_ultostr_zeropad(str, (tm->tm_year > 0) ? tm->tm_year : -(tm->tm_year - 1), 4);
```

The `BC` suffix is added [at the end of the function](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/datetime.c#l4387):

```
if (tm->tm_year <= 0)
{
  memcpy(str, " BC", 3);  /* Don't copy NUL */
  str += 3;
}
```

IMO this means that translating these values into `Day` should work the same way: If the `BC` suffix is present, subtract one from the year then negate it, e.g.

```
0005-01-01 BC ~> fromGregorianValid -4 1 1
0001-01-01 BC ~> fromGregorianValid 0 1 1
0001-02-29 BC ~> fromGregorianValid 0 2 29
```

**Comment by phadej** [comment]
I don't want to accept "looking at the code what it does" based reasoning. I'd welcome the reference to the docs. If docs are unclear, that is an issue in PostgreSQL.

**Comment by pbrinkmeier** [comment]
Afaict this is undocumented. There is documentation for the reverse case though:

https://www.postgresql.org/docs/current/datetime-input-rules.html

> 4. If BC has been specified, negate the year and add one for internal storage. (There is no year zero in the Gregorian calendar, so numerically 1 BC becomes year zero.)

While there isn't any documentation on the output format, there's some text on *why* Postgres uses the Gregorian calendar:

https://www.postgresql.org/docs/current/datetime-units-history.html

> PostgreSQL follows the SQL standard's lead by counting dates exclusively in the Gregorian calendar.

The SQL Standard requires that years can be in the range 1 AD-9999 AD, but Postgres supports 4713 BC-5874897 AD:

https://www.postgresql.org/docs/current/datatype-datetime.html

![image](https://github.com/haskellari/postgresql-simple/assets/5812813/93dd3168-6b38-4e9e-b4be-cd53dba6e57b)

The documentation for `SET DateStyle` says that Postgres uses ISO 8601 date formatting per the default setting:

https://www.postgresql.org/docs/7.2/sql-set.html

But ISO 8601 defines (section 4.1.2.4) an extended format for dates that is not observed by Postgres:

![image](https://github.com/haskellari/postgresql-simple/assets/5812813/e7fdab54-c794-4c7f-a3b9-9ba25ff5b1e5)

So I guess the `BC` suffix is truly undocumented for date and datetime output :(
