### ISSUE TITLE
Merge LSN support?

### ISSUE THREAD

**Issue by iand675** [haskellari/postgresql-simple#13]
Hi, wondering if you'd be willing to merge these two PRs?

- https://github.com/lpsmith/postgresql-simple/pull/259
- https://github.com/lpsmith/postgresql-simple/pull/260

260 builds upon 259, so there is some overlap in the commits.

**Comment by phadej** [comment]
OID handling have slightly changed, so there will be conflict. Also some tests would be nice

**Comment by phadej** [comment]
ping @iand675. Please make PR to this repository. I won't port PRs from lpsmith's one.

**Comment by phadej** [comment]
Closing as there is no response.
