### ISSUE TITLE
instance FromField Word

### ISSUE THREAD

**Issue by greydot** [haskellari/postgresql-simple#25]
The subject instance is lacking, but there is instance ToField Word. Is this intentional? Otherwise I'll submit a PR fixing this issue.

**Comment by phadej** [comment]
I'm not sure.

`FromField` instance check field types, and there aren't unsigned type in postgres. `ToField` is more lenient.

In other words, the problem is how to represent unsigned integers in postgres: simple check, domain type, https://github.com/petere/pguint 

I'm leaning towards "no solution", but provide a helpers for writing instances for `newtype`s.

**Comment by greydot** [comment]
Not sure that's a good one though. As a user, I'd expect fromField . toField == id to some degree. I suppose this could be implemented by mapping Word to the same type that toField does (int4 or int8, depending on the platform) and then checking for negative values.

**Comment by phadej** [comment]
Yes, you could do that (check for the underflow), but I think you shouldn't query for `Word`. Query for `Int` or application specific `newtype`. Having raw `Word` feels fishy. What's your motivational example?

**Comment by greydot** [comment]
>What's your motivational example?

The same as with Int, basically. It's a useful general-purpose type.

**Comment by phadej** [comment]
I counter that with: communicating with database is not "general". I think that avoiding `Word` in queries will make everything better, though requiring a small up-front cost.

i.e. I'm not convinced.

**Comment by phadej** [comment]
For the reference, previous discussion at least in https://github.com/lpsmith/postgresql-simple/issues/225

And `Param Word*` instances (renamed later to `ToField`) have been there from very beginning, see https://github.com/lpsmith/postgresql-simple/commit/32c3648b5feca7e3562bd93abfa84c32ad76714a#diff-d579b2ccc11b2d42fc0a134a6fd2f383R146

---

I have to think about `fromField . toField = id`. It's desirable, but there is "postgresql magic" in between (in a dot), which makes story complicated. Let's think about a principle.

**Comment by greydot** [comment]
>I have to think about fromField . toField = id. It's desirable, but there is "postgresql magic" in between (in a dot), which makes story complicated. Let's think about a principle.

I'd say this requires injectivity for mapping between haskell and postgresql types. Reworking the API into a single class with functional dependencies between haskell and postgresql types could help, I guess. But yeah, this is more than just adding a single instance.

**Comment by phadej** [comment]
I cannot find compelling reason for providing bare `Word` instance. Use a `newtype`.
