### ISSUE TITLE
Missing git tag for v0.5.4.0

### ISSUE THREAD

**Issue by 3noch** [haskellari/postgresql-simple#33]

**Comment by phadej** [comment]
It was NMU, so the tag is at in https://github.com/hackage-trustees/postgresql-simple/releases, I'll push it in this repo soon. Thanks for spotting

**Comment by 3noch** [comment]
Oh didn't know that existed! Thanks.

**Comment by phadej** [comment]
That took a bit longer... Now it's pushed.
