### ISSUE TITLE
Sharing DB connection across multiple threads?

### ISSUE THREAD

**Issue by saurabhnanda** [haskellari/postgresql-simple#36]
I tried searching for `thread` and `concurrent` in this repo, but couldn't find any relevant docs or discussion on this topic.

I'm writing a typical RDBMS-backed webapp, where every req/res involves talking to the DB. So, at the very top, a DB-connection is taking from a global `Connection Pool` and shoved into the `ReaderT Env` in which the handler is evaluated/executed.

However, there are certain cases where we need to fork multiple thread from within the handler, to parallelize certain computations. And I'm always worried whether I should write my own `forkWithNewDbConnection` function, or I can use `async / forkIO` and share the same DB connection across multiple thread.

Does this answer depend on:

- Are the threads doing only read operations concurrently?
- Are the threads doing read/write ops but NOT wrapped in a DB-txn?
- Are the thread doing read/write ops but INSIDE a DB-txn?
- It doesn't depend on anything -- don't share the same DB connection across concurrent threads.

If connection sharing across thread is not possible, is there any way to prevent the DB connection from being "leaked" into other threads (at a compiler/type-safe level)?

**Comment by sharno** [comment]
I think looking at the source, it seems that `Connection` internally is using `MVar`:
https://hackage.haskell.org/package/postgresql-simple-0.6.2/docs/src/Database.PostgreSQL.Simple.Internal.html#Connection

I think it's safe to assume that `Connection` is thread safe

**Comment by phadej** [comment]
Yes. `Connection` is backed by `MVar`.

That said, I would **not** recommend wrapping whole web handler in a single `withConnection` or `withResource`. You'll have a mostly idle connection for the most time, eating up the resources. (Concurrency of your whole webapp is limited by concurrency of your database connection pool).
