### ISSUE TITLE
'interval' column type is not supported

### ISSUE THREAD

**Issue by pawurb** [haskellari/postgresql-simple#59]
Hi. It looks like the lib does not support 'interval' column type. Sample query:

```sql
select interval '1 minute';
```

Would it be possible to include it? I'm just getting started with Haskell but maybe `NominalDiffTime` could work here?

**Comment by roelvandijk** [comment]
See https://github.com/lpsmith/postgresql-simple/issues/176 for a discussion about `FromField NominalDiffTime`.
In short: PostgreSQL interval can include months. You can't correctly convert months to days without context.

See https://github.com/lpsmith/postgresql-simple/pull/219 for a Haskell type which exactly matches a PostgreSQL interval.

**Comment by phadej** [comment]
See https://github.com/haskellari/postgresql-simple/pull/60
