### ISSUE TITLE
Support base-4.17

### ISSUE THREAD

**Issue by parsonsmatt** [haskellari/postgresql-simple#96]
#95 

Tested from `persistent` and `opaleye` via `allow-newer`

**Comment by tomjaguarpaw** [comment]
@phadej Is there anything we can do to get this bound bumped? I don't fully understand [CONTRIBUTING.md](https://github.com/haskellari/postgresql-simple/blob/master/CONTRIBUTING.md). This is not "a source code change" but does require "a patch to support newer base/GHC version". So I guess it does require changing `tested-with` and `haskell-ci.yml`. In which case does it help you if someone submits a patch to do that?

**Comment by phadej** [comment]
> In which case does it help you if someone submits a patch to do that?

No.

**Comment by phadej** [comment]
Done in https://github.com/haskellari/postgresql-simple/pull/103
