### ISSUE TITLE
Format error in an UPDATE statement

### ISSUE THREAD

**Issue by CGenie** [haskellari/postgresql-simple#98]
Hello,

I have this query:

```
[sql| UPDATE x
                    SET a = ?
                    WHERE b = ? AND c = ? AND d IN (SELECT id FROM y WHERE A = ?) |]
```
This works perfectly fine when I substitute some values and execute as a raw SQL statement.

However when I try to `Database.PostgreSQL.Simple.execute` this query with some values, I'm getting this error:

```
*** Exception: FormatError {fmtMessage = "syntax error in multi-row template", fmtQuery = "UPDATE x SET a = ? WHERE b = ? AND c = ? AND d IN (SELECT id FROM y WHERE A = ?)", fmtParams = []}
```

Apparently the internal parser for SQL for `postgresql-simple` can't handle this query properly.

**Comment by phadej** [comment]
are you sure you are calling `execute` and not `executeMany`?

A standalone reproducer using `formatQuery` would be great.

**Comment by CGenie** [comment]
Yes, it's `executeMany` but I thought they're just like a map over `execute` and I wanted to simplify my example.

**Comment by phadej** [comment]
> I thought they're just like a map over execute and I wanted to simplify my example.

it's not. It expands `VALUS (?,?)` into many tuples, so only one statement is executed.

**Comment by CGenie** [comment]
Ah OK I get it. So I should do `mapM (execute c query) params` in my case instead of `executeMany` directly?

**Comment by CGenie** [comment]
Yeah, `mapM` worked for me. Thanks for solving this!
